---
site: workflowr::wflow_site
title: Home
---

## Inference

### Likelihood Ratio and Likelihood

* [Likelihood Ratio for fully specified models, discrete data](likelihood_ratio_simple_models.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/likelihood_ratio_simple_models.pdf))
* [Likelihood Ratio for fully specified models, continuous data](likelihood_ratio_simple_continuous_data.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/likelihood_ratio_simple_continuous_data.pdf))
* Likelihood Ratios: Examples and Pitfalls
    - [Examples and Pitfalls](likelihood_do_dont.html)
    - [Example: LRs must be computed on same data](LR_error.html)
* [Likelihood Ratios: how big is convincing?](LR_and_BF.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/LR_and_BF.pdf))
* [Likelihood Ratios: Wilks's Theorem](wilks.html)
* [The Likelihood Function](likelihood_function.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/likelihood_function.pdf))
* [Asymptotic Normality of MLE](asymptotic_normality_mle.html)

### Bayesian Inference

* [Bayesian inference for comparing two fully-specified models](LR_and_BF.html)
* [Bayesian inference for comparing multiple fully-specified models](bayes_multiclass.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/bayes_multiclass.pdf))
* [Bayesian inference for a continuous parameter: analytic calculation](bayes_beta_binomial.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/bayes_beta_binomial.pdf))
* [Bayesian inference for a continuous parameter: summarizing the posterior](summarize_interpret_posterior.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/summarize_interpret_posterior.pdf))
* [Bayesian inference for a continuous parameter: conjugacy](bayes_conjugate.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/bayes_conjugate.pdf))
* [Bayesian inference for a normal mean](bayes_conjugate_normal_mean.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/bayes_conjugate_normal_mean.pdf))
* [Bayesian inference for a normal mean (shiny app illustration)](shiny_normal_example.html)
* [Bayesian inference for multiple independent parameters](bayes_independent.html)

### Empirical Bayes

* [The Empirical Bayes Normal Means problem](ebnm_normal.html)

### Frequentist vs Bayesian Inference

* [The difficulty calibrating p values](pvalue_difficult_calibrate_example.html)
* [Relationship between Bayes Factor and p value](BF_and_pvalue.html)
* [Conditional coverage of a standard normal CI](CI_conditional_coverage.html)

### Decision Theory

*  [Making a decision under uncertainty: the two class problem](decisions_costs_intro.html)
*  [Brief introduction to decision theory for prediction problems](decision_theory_bayes_rule.html)

### Mixture Models

* [Introduction to Mixture Models](mixture_models_01.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/mixture_models_01.pdf))
* [Introduction to the EM algorithm](em_algorithm_01.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/em_algorithm_01.pdf))
* [A variational view of the EM algorithm](em_variational.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/em_variational.pdf))
* [EM for Gaussian Mixture Models](intro_to_em.html)
* [Archive: Alternative Introduction to Mixture Models](intro_to_mixture_models.html)

### Bayesian Computation

* [Every Bayesian computation is an integral (or a sum)](integral.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/integral.pdf))
* [Importance sampling](Importance_sampling.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/Importance_sampling.pdf))

### Markov Chain Monte Carlo

* [The Metropolis-Hastings algorithm, Part 1](MH_intro.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/MH_intro.pdf))
* [The Metropolis-Hastings algorithm, Part 2](MH_intro_02.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/MH_intro_02.pdf))
* [Simple examples of Metropolis-Hastings algorithm](MH-examples1.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/MH-examples1.pdf))
* [Introduction to Gibbs sampling](gibbs1.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/gibbs1.pdf))
* [Gibbs sampling for a univariate normal mixture](gibbs2.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/gibbs2.pdf))
* [Gibbs sampling for a mixture of product-Bernoullis](gibbs_structure_simple.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/gibbs_structure_simple.pdf))

### Variational inference

* [Variational inference: approximations, objectives and algorithms](variational_inference.html)

### Hidden Markov Models

* [Forwards Backwards calculation example](hmm.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/hmm.pdf))

## Distributions

* [The Beta Distribution](beta.html)
* [The Dirichlet Distribution](dirichlet.html)
* [The Pólya--Gamma Distribution](polya_gamma.html)

## Stochastic Processes

### Discrete-Time Markov Chains

* [Discrete-Time Markov Chains: Introduction](markov_chains_discrete_intro.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/markov_chains_discrete_intro.pdf))
* [Discrete-Time Markov Chains: Finding the Stationary Distribution via solution of the global balance equations](stationary_distribution.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/stationary_distribution.pdf))
* [Discrete-Time Markov Chains: Finding the Stationary Distribution via eigendecomposition](markov_chains_discrete_stationary_dist.html)
* [Simulating Discrete-Time Markov Chains: An Introduction](simulating_discrete_chains_1.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/simulating_discrete_chains_1.pdf))
* [Simulating Discrete-Time Markov Chains: Limiting Distributions](simulating_discrete_chains_2.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/simulating_discrete_chains_2.pdf))

### Poisson Processes

*  [Poisson Processes: Thinning with time-dependent probabilities](poisson_process_time_dependent_thinning.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/poisson_process_time_dependent_thinning.pdf))
*  [Poisson Process: The Limiting Case of the Bernoulli Process](bernoulli_poisson_process.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/bernoulli_poisson_process.pdf))

### Methods for sampling non-standard distributions

* [Inverse transform sampling](inverse_transform_sampling.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/inverse_transform_sampling.pdf))

### Multivariate Normal

* [A key property of univariate normal](norm_linear_comb.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/norm_linear_comb.pdf))
* [Bivariate normal distribution](mvnorm_00.html)
* [Multivariate Normal](mvnorm.html)
* [The precision matrix](normal_markov_chain.html)
* [Interpreting $N(\mu,\Sigma)$ via eigen-decomposition of $\Sigma$](mvnorm_eigen.html)

### Gaussian Process

* [Introduction to Gaussian Processes](gaussian_process.html)

## Population Genetics

* [Simulating from a simple genetic mixture model](r_simplemix.html) ([PDF](https://github.com/pcarbo/fiveMinuteStats/blob/master/docs/r_simplemix.pdf))
* [Wright-Fisher Model](wright_fisher_model.html)
* [Wright-Fisher Model Approximations](approx_wright_fisher_model.html)
